name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente à meia-noite (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: yagowalter # Seu nome de usuário
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # O branch 'output' será criado para guardar o GIF/SVG
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
