name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente à meia-noite (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: yagowalter
          outputs: |
            # Este é o arquivo SVG com o tema Dracula
            dist/snake-dracula.svg?palette=dracula&color_theme=dracula 
          # Você pode remover as outras linhas de 'outputs' se quiser apenas o Dracula

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # O branch 'output' será criado para guardar o GIF/SVG
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
